name: DartNodeTreeSanitizers
version: 0.0.0-alpha.1
description: A colection of TreeSanitizers
author: Jose Angel Espinoza Portillo <onlyangelred@gmail.com>
homepage: http://a.ngel.es
dependencies:
  browser: ">=0.9.1 <0.9.2"
