name: dart_node_tree_sanitizers
version: 0.0.0-alpha.2
description: A colection of TreeSanitizers
author: Jose Angel Espinoza Portillo <onlyangelred@gmail.com>
homepage: http://a.ngel.es
dependencies:
  browser: ">=0.10.0+2 <0.11.0"
